// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Olf1yZqucZcGZroiotO7P0DzzwuOPf4',
    appId: '1:190917452882:web:c0360230482cc3349bab8b',
    messagingSenderId: '190917452882',
    projectId: 'premium-car-hub',
    authDomain: 'premium-car-hub.firebaseapp.com',
    storageBucket: 'premium-car-hub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUyqb1TxWSYHHbyU9XlyZMB8MmJ0AF_N0',
    appId: '1:190917452882:android:942b6b4d6b5694bb9bab8b',
    messagingSenderId: '190917452882',
    projectId: 'premium-car-hub',
    storageBucket: 'premium-car-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWREbyK3ffIEO0gzUuiYDUp5FeKUpbO5g',
    appId: '1:190917452882:ios:4a2b253374aff36d9bab8b',
    messagingSenderId: '190917452882',
    projectId: 'premium-car-hub',
    storageBucket: 'premium-car-hub.firebasestorage.app',
    iosBundleId: 'com.example.carMarketplaceAndRentManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWREbyK3ffIEO0gzUuiYDUp5FeKUpbO5g',
    appId: '1:190917452882:ios:4a2b253374aff36d9bab8b',
    messagingSenderId: '190917452882',
    projectId: 'premium-car-hub',
    storageBucket: 'premium-car-hub.firebasestorage.app',
    iosBundleId: 'com.example.carMarketplaceAndRentManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4Olf1yZqucZcGZroiotO7P0DzzwuOPf4',
    appId: '1:190917452882:web:55188b4247ddb2c79bab8b',
    messagingSenderId: '190917452882',
    projectId: 'premium-car-hub',
    authDomain: 'premium-car-hub.firebaseapp.com',
    storageBucket: 'premium-car-hub.firebasestorage.app',
  );
}
